"""Table mapping for the local ETL."""

from . import cleaning as C
from .party_catalog import active_party_ideology_rows


PARTIDOS_IDEOLOGIA = active_party_ideology_rows()


LOAD_ORDER = [
    "deputados",
    "partidos_ideologia",
    "proposicoes",
    "eventos",
    "votacoes",
    "gastos",
    "votacoes_votos",
    "votacoes_orientacoes",
    "votacoes_objetos",
    "proposicoes_temas",
    "eventos_presenca_deputados",
    "proposicoes_autores",
]

ALL_TABLES_ORDERED = LOAD_ORDER[:]


TABLES = {
    "deputados": {
        "file": "deputados.csv",
        "table": "deputados",
        "pk": ["id_deputado"],
        "required": ["id_deputado", "uri_deputado", "nome"],
        "skip_identity": [],
        "transform": "deputados",
        "columns": {
            "uri": ("uri_deputado", C.clean_text),
            "nome": ("nome", C.clean_text),
            "nomeCivil": ("nome_civil", C.clean_text),
            "cpf": ("cpf", C.clean_cpf),
            "idLegislaturaInicial": ("id_legislatura_inicial", C.clean_int),
            "idLegislaturaFinal": ("id_legislatura_final", C.clean_int),
        },
    },
    "partidos_ideologia": {
        "file": None,
        "table": "partidos_ideologia",
        "pk": ["sigla_partido"],
        "required": ["sigla_partido", "ideologia"],
        "skip_identity": [],
        "generated_rows": PARTIDOS_IDEOLOGIA,
        "columns": {
            "sigla_partido": ("sigla_partido", C.clean_party),
            "ideologia": ("ideologia", C.clean_text),
        },
    },
    "proposicoes": {
        "file_pattern": "proposicoes-*.csv",
        "table": "proposicoes",
        "year_from_file": True,
        "pk": ["ano_dados", "id_proposicao"],
        "required": ["ano_dados", "id_proposicao", "uri_proposicao"],
        "skip_identity": [],
        "columns": {
            "id": ("id_proposicao", C.clean_int),
            "uri": ("uri_proposicao", C.clean_text),
            "siglaTipo": ("sigla_tipo", C.clean_upper),
            "numero": ("numero", C.clean_int),
            "ano": ("ano", C.clean_int),
            "ementa": ("ementa", C.clean_text),
            "ementaDetalhada": ("ementa_detalhada", C.clean_text),
            "keywords": ("keywords", C.clean_text),
            "ultimoStatus_descricaoSituacao": ("descricao_situacao", C.clean_text),
        },
    },
    "eventos": {
        "file_pattern": "eventos-*.csv",
        "table": "eventos",
        "year_from_file": True,
        "pk": ["ano_dados", "id_evento"],
        "required": ["ano_dados", "id_evento"],
        "skip_identity": [],
        "columns": {
            "id": ("id_evento", C.clean_int),
            "uri": ("uri_evento", C.clean_text),
            "dataHoraInicio": ("data_hora_inicio", C.clean_timestamp),
            "dataHoraFim": ("data_hora_fim", C.clean_timestamp),
            "descricaoTipo": ("descricao_tipo", C.clean_text),
            "descricao": ("descricao", C.clean_text),
            "localCamara.nome": ("local_camara", C.clean_text),
        },
    },
    "votacoes": {
        "file_pattern": "votacoes-*.csv",
        "table": "votacoes",
        "year_from_file": True,
        "pk": ["ano_dados", "id_votacao"],
        "required": ["ano_dados", "id_votacao"],
        "skip_identity": [],
        "transform": "votacoes",
        "columns": {
            "id": ("id_votacao", C.clean_text),
            "data": ("data_votacao", C.clean_date),
            "siglaOrgao": ("sigla_orgao", C.clean_upper),
            "idEvento": ("id_evento", C.clean_int),
            "aprovacao": ("aprovacao", C.clean_boolean),
            "descricao": ("descricao", C.clean_text),
        },
    },
    "gastos": {
        "file_pattern": "Ano-*.csv",
        "table": "gastos",
        "year_from_file": True,
        "pk": [],
        "required": ["ano_dados", "id_deputado", "nome_parlamentar", "sigla_uf", "sigla_partido", "valor_liquido"],
        "skip_identity": ["id_gasto"],
        "columns": {
            "cpf": ("cpf", C.clean_cpf),
            "ideCadastro": ("id_deputado", C.clean_int),
            "txNomeParlamentar": ("nome_parlamentar", C.clean_text),
            "sgUF": ("sigla_uf", C.clean_upper),
            "sgPartido": ("sigla_partido", C.clean_party),
            "vlrDocumento": ("valor_documento", C.clean_money),
            "vlrGlosa": ("valor_glosa", C.clean_money),
            "vlrLiquido": ("valor_liquido", C.clean_money),
            "txtDescricao": ("descricao_despesa", C.clean_text),
            "txtFornecedor": ("fornecedor", C.clean_text),
        },
        "drop_if": "lideranca",
    },
    "votacoes_votos": {
        "file_pattern": "votacoesVotos-*.csv",
        "table": "votacoes_votos",
        "year_from_file": True,
        "pk": ["ano_dados", "id_votacao", "id_deputado"],
        "required": ["ano_dados", "id_votacao", "id_deputado", "voto", "nome_deputado"],
        "skip_identity": [],
        "columns": {
            "idVotacao": ("id_votacao", C.clean_text),
            "deputado_id": ("id_deputado", C.clean_int),
            "voto": ("voto", C.clean_vote),
            "deputado_nome": ("nome_deputado", C.clean_text),
            "deputado_siglaPartido": ("sigla_partido", C.clean_party),
            "deputado_siglaUf": ("sigla_uf", C.clean_upper),
        },
    },
    "votacoes_orientacoes": {
        "file_pattern": "votacoesOrientacoes-*.csv",
        "table": "votacoes_orientacoes",
        "year_from_file": True,
        "pk": ["ano_dados", "id_votacao", "sigla_bancada"],
        "required": ["ano_dados", "id_votacao", "sigla_bancada"],
        "skip_identity": [],
        "columns": {
            "idVotacao": ("id_votacao", C.clean_text),
            "siglaBancada": ("sigla_bancada", C.clean_party),
            "orientacao": ("orientacao", C.clean_vote),
            "siglaOrgao": ("sigla_orgao", C.clean_upper),
            "descricao": ("descricao", C.clean_text),
        },
    },
    "votacoes_objetos": {
        "file_pattern": "votacoesObjetos-*.csv",
        "table": "votacoes_objetos",
        "year_from_file": True,
        "pk": [],
        "required": ["ano_dados", "id_votacao"],
        "skip_identity": ["id_votacao_objeto"],
        "columns": {
            "idVotacao": ("id_votacao", C.clean_text),
            "proposicao_id": ("id_proposicao", C.clean_int),
            "proposicao_uri": ("uri_proposicao", C.clean_text),
            "proposicao_titulo": ("titulo_proposicao", C.clean_text),
            "proposicao_ementa": ("ementa_proposicao", C.clean_text),
            "proposicao_siglaTipo": ("sigla_tipo_proposicao", C.clean_upper),
            "proposicao_numero": ("numero_proposicao", C.clean_int),
            "proposicao_ano": ("ano_proposicao", C.clean_int),
        },
    },
    "proposicoes_temas": {
        "file_pattern": "proposicoesTemas-*.csv",
        "table": "proposicoes_temas",
        "year_from_file": True,
        "pk": ["ano_dados", "uri_proposicao", "cod_tema"],
        "required": ["ano_dados", "uri_proposicao", "cod_tema", "tema"],
        "skip_identity": [],
        "columns": {
            "uriProposicao": ("uri_proposicao", C.clean_text),
            "codTema": ("cod_tema", C.clean_int),
            "tema": ("tema", C.clean_text),
            "relevancia": ("relevancia", C.clean_decimal),
        },
    },
    "eventos_presenca_deputados": {
        "file_pattern": "eventosPresencaDeputados-*.csv",
        "table": "eventos_presenca_deputados",
        "year_from_file": True,
        "pk": ["ano_dados", "id_evento", "id_deputado"],
        "required": ["ano_dados", "id_evento", "id_deputado"],
        "skip_identity": [],
        "columns": {
            "idEvento": ("id_evento", C.clean_int),
            "idDeputado": ("id_deputado", C.clean_int),
            "nomeDeputado": ("nome_deputado", C.clean_text),
            "siglaPartido": ("sigla_partido", C.clean_party),
            "siglaUf": ("sigla_uf", C.clean_upper),
        },
    },
    "proposicoes_autores": {
        "file_pattern": "proposicoesAutores-*.csv",
        "table": "proposicoes_autores",
        "year_from_file": True,
        "pk": [],
        "required": ["ano_dados", "id_proposicao", "nome_autor", "tipo_autor"],
        "skip_identity": ["id_autoria"],
        "columns": {
            "idProposicao": ("id_proposicao", C.clean_int),
            "uriProposicao": ("uri_proposicao", C.clean_text),
            "idDeputadoAutor": ("id_deputado", C.clean_int),
            "nomeAutor": ("nome_autor", lambda v: C.clip_text(v, 200)),
            "tipoAutor": ("tipo_autor", C.clean_text),
            "siglaPartidoAutor": ("sigla_partido", C.clean_party),
            "siglaUFAutor": ("sigla_uf", C.clean_upper),
            "ordemAssinatura": ("ordem_assinatura", C.clean_int),
            "proponente": ("peso_autoria", C.clean_decimal),
        },
    },
}
